### ISSUE TITLE
Experimental json output is not compatible with BigQuery

### ISSUE THREAD

**Issue by mab-happtiq** [opensnowcat/opensnowcat-enrich#223]
Hi, first of all thanks for your efforts in providing this repo and new features

I deployed 1.1.0 and using config 
```
{
  ...
  "experimental": {
    "customOutputFormat": {
      "type": "FlattenedJson"
    }
  }
  ...
}
```
I  am using pubsub bigquery subscription but the writing to bq does not work because of date/time/timestamp need to be integer in the JSON according to https://cloud.google.com/pubsub/docs/bigquery#date_time_int

could we plan a fix here. I am also open to contribute/open a PR if needed

**Comment by AlexITC** [comment]
Thanks for reporting this, at this stage, it would be ideal if you can prepare a PR.

It seems that we should propagate acustom JSON encoder when using BigQuery.

**Comment by AlexITC** [comment]
Please fork the repository and submit a Pull Request.

**Comment by AlexITC** [comment]
Released by https://github.com/opensnowcat/opensnowcat-enrich/releases/tag/1.2.0

Thanks.
